### PR TITLE
Allow to compile the extension everywhere

### LINKED ISSUE #15: import rocksdb issuse:  undefined symbol: _ZTIN7rocksdb10ComparatorE
1.Collecting python-rocksdb
Requirement already satisfied: setuptools in /home/guosheng/.local/lib/python2.7/site-packages (from python-rocksdb)
Installing collected packages: python-rocksdb
Successfully installed python-rocksdb-0.6.7
2.
guosheng@guosheng:~/code/db_rock/rocksdb/pyrocks_test$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python2.7/dist-packages/rocksdb/_rocksdb.so: undefined symbol: _ZTIN7rocksdb10ComparatorE
>>>

### PR DESCRIPTION
**Pull request by sileht**
This change:
* uses to setuptools Cython automatic extension build system.
* Add tox.ini to run tests and build docs into virtualenv
* Add .travis.yaml and Dockerfile to run tests in CI
* Change requirements to ensure:
  - Cython and setuptools are installed before we build the Cython
    extension
  - tests dependencies are not installed by default
  - doc dependencies are explicit
* Add missing lz4 library
* Allow to build the module with any librocksdb headers (no-rtti)

Closes #15

### CODE REVIEW

**Comment by sileht** [comment]
Pull-request updated, HEAD is now e8de1ea7462d0650e923d9322e682a6f76704518

**Comment by sileht** [comment]
You can see the result of the travis CI: https://travis-ci.org/sileht/python-rocksdb/builds/339353563

**Comment by twmht** [comment]
@sileht 

thanks! I will merge this PR in a few days.

**Comment by sileht** [comment]
Don't forget to enable travis on your repo to enable it :)

**Pull request merged**
