### PR TITLE
Column Family Support

### PR DESCRIPTION
**Pull request by fried**
- Add support for Column Families in a runtime safe way. 
use weakrefs so insure that when a db is closed (Garbage collected, all of its Column Families are closed first).   This prevents rocksdb from performing an assert exit of the process. 
- Add unittests to test functionality
- Insure all unittests are passing.
- Cleaned up unittests to not use a fixed directory in tmp, but use tempfile. 

Any operation that handles keys can also handle column families by accepting a tuple(ColumnFamilyHandle, key)  any operation that returns keys when used with ColumnFamilies will return them in the same way.

### CODE REVIEW

**Comment by fried** [comment]
I inadvertently included the fix for StringAppendOperator to work for python3.

**Comment by twmht** [comment]
@fried 

thank you. The review is ongoing.

**Comment by hwind** [comment]
When will this PR be merged? I'm looking forward :)

**Comment by ingvarbiz** [comment]
Can you please proceed with that PR? Column Family support will help me a lot in my current project. Thank you!

**Comment by iFA88** [comment]
Can you give some tutorial, how can be open an existing database which has column families? I get `rocksdb.errors.InvalidArgument: Invalid argument: You have to open all column families. Column families not opened: ......` when i want to open my database.

Thank you!

**Pull request merged**
